data:
  label_list: congvan
  martname: congvan
  max_sample: 2000
  test_dir: ../data/congvan/test
  train_dir: ../data/congvan/train
  val_dir: ../data/congvan/val
model:
  dropout_rate: 0.5
  emb_dim: 128
  emb_range: 640
  l2_reg: 0.01
  text_feature_dim: 314
options:
  model_type: rgcn
  more_feature: false
  sort_bbs: true
  use_emb: true
  word_encoder:
    dim: 300
    lang: vi
    vs: 100000
training:
  base_lr: 0.0003
  ckpt_save_dir: ckpt_models/congvan/
  exp_description: rgcn_7_layers_augment
  label_smoothing: 0.02
  num_epoch: 10
  optimizer: AdamW
  prev_ckpt_path: null
  use_warmup: false
  warmup_ratio: 0.05
  weight_decay: 0.0005
